spring:
  data:
    mongodb:
      database: yudream
      host: localhost
      port: 27017
    redis:
      host: localhost
      port: 6379
    minio:
      host: localhost
      port: 9000
      username: minioadmin
      password: minioadmin
      bucket: yudream
  thymeleaf:
    cache: false
  mail:
    host: smtp.feishu.cn
    username: yudream@yudream.online
    password: "ptYOqysamo2KykPm"
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
server:
  address: 0.0.0.0
default-user:
  username: admin
  password: admin
passkey:
  rpId: localhost
  rpName: Yudream Passkey Demo
  origins: http://localhost:8080
