spring:
  data:
    mongodb:
      database: yudream
      host: localhost
      port: 27017
    redis:
      host: localhost
      port: 6379
    minio:
      host: localhost
      port: 9000
      username: minioadmin
      password: minioadmin
      bucket: yudream
  thymeleaf:
    cache: false
server:
  address: 0.0.0.0
default-user:
  username: admin
  password: admin