spring:
  profiles:
    active: dev
security:
  excluded-urls:
    urls:
      - /login
      - /register
      - /forget
      - /
      - /404
      - /css/**
      - /js/**
      - /favicon.ico
      - /assets/**
      - /captcha/**
